version: '3'

services:
  db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=ayda
      - POSTGRES_PASSWORD=aydaPwd
    volumes:
      - "ayda_val_db_data:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - mail_val_backend_tier


  ayda:
    restart: always
    build: .
    depends_on:
      - db
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8009
    environment:
      - DJANGO_COLLECT_STATIC=off
      - DJANGO_MANAGEPY_MIGRATE=off
    links:
      - db:postgres
    ports:
      - "8009:8009"
    volumes:
      - .:/app
    networks:
    - mail_val_backend_tier


volumes:
  ayda_val_db_data:
    driver: local
  static_volume:
    driver: local

networks:
  mail_val_backend_tier:
    driver: bridge


